### ISSUE TITLE
multiple VPN tunnels on the same Linux host

### ISSUE THREAD

**Issue by dkhokhlov** [NordSecurity/nordvpn-linux#10]
Is it possible to setup multiple VPN tunnels on the same Linux host?

**Comment by dkhokhlov** [comment]
Use case:
- multiple tun ifaces to nordvpn with different IPs
possible?

what is "multiple meshnet connections simultaneously"?

**Comment by Savolro** [comment]
Hi! Your use case is not supported by the app and currently we are not planning to support it.

Regarding multiple meshnet connections, there is a single tun interface called "nordlynx" but it has active WireGuard connections to multiple nodes at the same time. If the nodes allow exit node routing, you could use them as VPN servers but you'd need to set your routing up accordingly on your own as app only allows you to route through a single meshnet peer.

In case you'd wish to set up this on your own, you could try to combine multiple configurations of either OpenVPN (e. g. by https://support.nordvpn.com/Connectivity/Linux/1047409422/Connect-to-NordVPN-using-Linux-Terminal.htm) or NordLynx (e. g. by connecting to the VPN via app and using [wireguard-tools](https://github.com/WireGuard/wireguard-tools)) into a single one to match your use case.

**Comment by dkhokhlov** [comment]
> tun interface called "nordlynx" but it has active WireGuard connections to multiple nodes at the same time

how to get a list of these peers (nodes)?

> If the nodes allow exit node routing, you could use them as VPN servers

how to known which peers from that list support the exit node routing?

**Comment by dkhokhlov** [comment]
By " list of these peers (nodes)" I  meant  NordVPN nodes in context what you said:

> If the nodes allow exit node routing, you could use them as VPN servers 

On NordVPN OpenVPN  theer are many server nodes to choose from.  It is not clear what nodes will be available through WireGuard  NordVPN tun iface, specifically external IPs.
