### ISSUE TITLE
quic transport needs reconnect

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/nordvpn-linux#15]
Where is this message from:
`nordvpnd[495]: 2023/03/26 14:09:36 quic transport needs reconnect, err: Application error 0x100 (remote)`
It was in daemonlog.txt from
`$ sudo journalctl -u nordvpnd > ./daemonlog.txt`

**Comment by keliramu** [comment]
Hi, this message is from backend API request `quic` / `http3` transport layer - server terminates inactive connection (and reports this situation as this error), so, connection has to be reestablished. This message looks like some error, but really it is not.

**Comment by keliramu** [comment]
Hi, @bjlockie, misleading log error was removed, check out this commit: [d156f47](https://github.com/NordSecurity/nordvpn-linux/commit/d156f47afb727528bf4e80818e1683f3db3a93fd).  
This small fix will be included with release of NordVPN next version soon.  
Closing this issue.
