### ISSUE TITLE
Terminal hangs after connecting and disconnecting

### ISSUE THREAD

**Issue by fedario** [NordSecurity/nordvpn-linux#209]
Hey,

whenever I connect or disconnect with the nordvpn cli application it does not give control back to the terminal (I've tried waiting for over 20 minutes).
However, I can try to call pkill nordvpn from another terminal, without sudo (!), so it shouldn't actually do anything, but it stops the hang and nordvpn says it is connected afterwards. Same for disconnecting.

Do you have any idea what could cause this?
I'm currently on openSUSE, however, I had the same issue under Ubuntu 22.04.

Here is a video showing the behavior:

https://github.com/NordSecurity/nordvpn-linux/assets/24253179/42227bab-fd80-446f-bf85-e94faa913b45

**Comment by bartoszWojciechO** [comment]
Hi, can you provide logs emitted by nordvpn daemon when connecting? Just `sudo journalctl -u nordvpnd > nordvpn.log` or something like that.

**Comment by piotrjurkiewicz** [comment]
Actually `pkill nordvpn` command matches any process containing the `nordvpn` in its name, so SIGTERM is send both to `nordvpnd` daemon and `nordvpn` command line utility. It does not have permissions to send a signal to `nordvpnd` since it is being run as a root (`Operation not permitted` errror), but it successfully kills the `nordvpn` command line utility, because it is being run as the user. So it is nothing wrong that `pkill nordvpn` unhangs the terminal, because it kills `nordvpn connect/disconnect` process. But it needs to be investigated why connect or disconnect commands do not finish after successful connection/disconnection.

**Comment by fedario** [comment]
@bartoszWojciechO 
The resulting file is quite big, so I used `sudo journalctl -u nordvpnd --since today > nordvpn.log` after doing the procedure shown in the video.  
Here is the file: [nordvpn.log](https://github.com/NordSecurity/nordvpn-linux/files/13810503/nordvpn.log)
I hope it doesn't contain any sensitive information.

@piotrjurkiewicz 
Ah, thank you for the clarification, I learned something new!

**Comment by bartoszWojciechO** [comment]
We censor or omit the sensitive stuff in the logs, so we should be safe in that regard. I didn't see anything out of ordinary in the logs.

Do you get the GUI notification popup when connecting? Could you try disabling notifications(`nordvpn set notify off`) and connecting? It's just a guess, but notifications are sent at the end, so maybe they are block the connection process from finishing.

**Comment by fedario** [comment]
@bartoszWojciechO 
No, I did not get any GUI popups and your hunch was correct: `nordvpn set notify off` fixed it!
It is a workaround, but I prefer having no popups anyway, so it's a great solution for me, thank you!

However, if there are things, I can do to help find the cause of the missing GUI popup, please don't hesitate to ask.

**Comment by bartoszWojciechO** [comment]
Hi @fedario, I'm happy to hear that.

As to determining the root cause, which desktop environment are you running? Can you send notifications with commands like `notify-send` or `kdialog`?

**Comment by fedario** [comment]
I'm running KDE.
`notify-send` is not a recognized command on my system, however, something like `kdialog --yesno "hi there"` does open a new dialogue as expected.

**Comment by mariusSincovici** [comment]
The issue should be fixed in the latest releases. 
Try to update to 3.17.4 and let us know if there are still any issues.
Thanks.
