### ISSUE TITLE
Meshnet peer nicknames

### ISSUE THREAD

**Issue by jjtkalt** [NordSecurity/nordvpn-linux#22]
It would be really helpful to allow assigning a node-nickname that would translate <username>-<mountain>.nord to <username>-<nickname>.nord so that the various connected peers can be easily identified by the user.  Having six to ten nodes named after mountains can be confusing when I'm specifically looking for my "home file share server" but four of the servers are the same OS, and I can't see the non-meshnet IP address of the server or the hostname.  (Thanks!)

**Comment by Savolro** [comment]
Hi and thank you for feature request! Peer renaming is already in our product backlog. We'll update this issue as well once we have updates.
