### ISSUE TITLE
nordvpn client on rastberry PI zero does not work

### ISSUE THREAD

**Issue by tsolodov** [NordSecurity/nordvpn-linux#227]
```
uname -a
Linux xxxx 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
```

```
$ file /usr/bin/nordvpn
/usr/bin/nordvpn: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, Go BuildID=A77UBy0ryYuKhMAtauZW/hPIExoS28CMZlu4N8Ho9/U9RlU9HbLzpRkxWXmbp-/KridFo84JH3EyZSD6NVa, BuildID[sha1]=0af7a84ffb23bb6da802f10466886e0fd096e6fe, stripped
```

```
$ cat /etc/apt/sources.list.d/nordvpn.list 
deb https://repo.nordvpn.com//deb/nordvpn/debian stable main
```

```
$ nordvpn
Segmentation fault
```
Installed version:
```
nordvpn/stable,now 3.16.9 armhf [installed]
```

**Comment by tsolodov** [comment]
![image](https://github.com/NordSecurity/nordvpn-linux/assets/8018497/55ce404c-095e-4f62-b55e-842e4a1ae116)

Please send me a link to a working build for rastberry PI zero/zero w2

**Comment by tsolodov** [comment]
![image](https://github.com/NordSecurity/nordvpn-linux/assets/8018497/7d604739-9ef2-4d68-8510-0642fe1f49b1)
Please send me a ling to a working build for zero W/zero 2 W

**Comment by mariusSincovici** [comment]
Hi,
If you're running Raspbian(Raspberry Pi OS), then the application is crashing for ARMv6 boards(including zero).

Could you try to install Debian instead and check with that? e.g.: https://raspi.debian.net/tested-images/, `2023.11.09 12 (Bookworm) 1 0W`

**Comment by tsolodov** [comment]
> Hi, If you're running Raspbian(Raspberry Pi OS), then the application is crashing for ARMv6 boards(including zero).
> 
> Could you try to install Debian instead and check with that? e.g.: https://raspi.debian.net/tested-images/, `2023.11.09 12 (Bookworm) 1 0W`

I can confirm it works on debian. Would be great to document this behavior

**Comment by mariusSincovici** [comment]
thanks for checking.
We've contacted our customer support team and they will update the documentation.
