### ISSUE TITLE
Make `nordvpn countries` output actually useful and usable to be fed to `nordvpn connect`

### ISSUE THREAD

**Issue by leledumbo** [NordSecurity/nordvpn-linux#23]
Hi, I was contributing to [NordTray](https://github.com/zoli/nordtray) to add country selection support, only to find out that `nordvpn countries` output a list that's not usable when fed to `nordvpn connect`, despite the help page says otherwise. For example:
```
$ nordvpn c Singapore
```
results in `The specified server is not available at the moment or does not support your connection settings.` but:
```
$ nordvpn c sg
```
works. Due to this, I must hit the [undocumented public API](https://github.com/zoli/nordtray/blob/master/nordvpn.go#L186) to get the country list alongside their code. I expect to get the useful list from `nordvpn countries` instead as I expect using an undocumented public API is kind of fragile.

**Comment by ph202107** [comment]
It seems to work OK for me.  I'm using Nord 3.16.2 on Linux Mint 20.3 and 21.1.

$ nordvpn connect France
Connecting to France #538 (fr538.nordvpn.com)
You are connected to France #538 (fr538.nordvpn.com)!

$ nordvpn connect Canada
Connecting to Canada #1685 (ca1685.nordvpn.com)
You are connected to Canada #1685 (ca1685.nordvpn.com)!

$ nordvpn connect Singapore
Connecting to Singapore #521 (sg521.nordvpn.com)
You are connected to Singapore #521 (sg521.nordvpn.com)!

I have encountered an occasional bug where connecting to known good servers by name (eg. nordvpn connect sg521) would produce the same error.  I can't replicate the cause of the bug, but I know that purging and reinstalling the app fixes it for me.

**Comment by leledumbo** [comment]
Ah, I just updated to 3.16.2 and indeed that now works, wasn't the case for 3.16.1. Looks like I'll have to keep the current approach for a while as 3.16.2 is still very fresh, maybe I'll change next month.
I do notice a difference, `nordvpn countries` returns 59 countries while that public API returns 60, to be precise what's missing is United Arab Emirates, although indeed the server there seems to be currently down or missing, as no UAE servers are listed in https://api.nordvpn.com/v1/servers.

**Comment by ph202107** [comment]
I'm not sure about the API, but in the app UAE is only available when the "Obfuscate" setting is enabled.  (This also reduces the country list to 16 countries that have obfuscation support.)

**Comment by leledumbo** [comment]
Indeed settings matter. This complicates things a little, but maybe I'll let it be in the mean time.

**Comment by ggediminass** [comment]
Hello,

It seems, that the issue discussed here was solved within the release of 3.16.3 NordVPN application version.

The reproduction of the issue was only possible, when Technology was set specifically to OpenVPN, and Obfuscation setting was enabled.
