### ISSUE TITLE
DNS leak after wake from suspend?

### ISSUE THREAD

**Issue by ph202107** [NordSecurity/nordvpn-linux#243]
Linux Mint 20.3 (bare metal), NordVPN version 3.17.0.  
IPv6 is disabled on system and NordVPN app.

Technology: NORDLYNX
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled
Allowlisted subnets:
	192.168.1.0/24

Steps to reproduce:
- connect to VPN
- visit https://dnscheck.tools/
- site correctly detects NordVPN exit IP and NordVPN DNS servers
- close browser
- suspend computer (via GUI)
- wait 5s
- wake computer
- 'nordvpn status' shows connected to the same server
- https://dnscheck.tools/ now detects the NordVPN exit IP and my ISP DNS servers

After disconnect and reconnect to VPN the NordVPN DNS servers are detected again.  
Also tested with version 3.16.9 and it is working OK.  I do not have the same problem when using 3.16.9, only 3.17.0 seems to be affected.

I have a Ubuntu VM for testing purposes, but I'm not able to Power-Off - Suspend from within the VM.  I appealed to the Reddit community for help testing but without success.

Please let me know if more information is required.  Thanks!

**Comment by mariusSincovici** [comment]
thank you for reporting the issues.
We've tried to reproduce this on our side but without success.
Would it be possible to send the output of the following command, if there are no sensitive info on side?
```
ip a
sudo iptables -S
sudo ip6tables -S
ip route show table all
ip -6 route show table all
ip rule
ip -6 rule
sysctl -a 2> /dev/null | grep disable_ipv6
nmcli dev show | grep -E 'DNS|CONNECTION'
```

Thanks

**Comment by ph202107** [comment]
Hi Marius!  Here is the output while I'm connected to VPN and the DNS is leaking after wake from suspend. 
The dnscheck site shows 8 DNS resolvers from my ISP, 4 have IP4 addresses and 4 have IP6 addresses. 
In the following comment I will add the output when DNS is working normally.

Technology: NORDLYNX
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled
Allowlisted subnets:
	192.168.1.0/24

Status: Connected
Hostname: us9444.nordvpn.com
IP: 64.44.80.131
Country: United States
City: Denver
Current technology: NORDLYNX
Current protocol: UDP
Transfer: 13.86 MiB received, 0.74 MiB sent
Uptime: 17 minutes 7 seconds


$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c8:d3:ff:a3:00:50 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.199/24 brd 192.168.1.255 scope global dynamic noprefixroute eno1
       valid_lft 86101sec preferred_lft 86101sec
3: nordlynx: <POINTOPOINT,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.5.0.2/32 scope global nordlynx
       valid_lft forever preferred_lft forever

$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s 192.168.1.0/24 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A INPUT -p udp -m multiport --dports 4000,5353 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 4000 -j ACCEPT
-A INPUT -p udp -m multiport --dports 5353 -j ACCEPT
-A OUTPUT -d 192.168.1.0/24 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ sudo ip6tables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A INPUT -p udp -m multiport --dports 4000,5353 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 4000 -j ACCEPT
-A INPUT -p udp -m multiport --dports 5353 -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ ip route show table all
default dev nordlynx table 205 scope link 
default via 192.168.1.254 dev eno1 proto dhcp metric 20100 
169.254.0.0/16 dev eno1 scope link metric 1000 
192.168.1.0/24 dev eno1 proto kernel scope link src 192.168.1.199 metric 100 
local 10.5.0.2 dev nordlynx table local proto kernel scope host src 10.5.0.2 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 192.168.1.0 dev eno1 table local proto kernel scope link src 192.168.1.199 
local 192.168.1.199 dev eno1 table local proto kernel scope host src 192.168.1.199 
broadcast 192.168.1.255 dev eno1 table local proto kernel scope link src 192.168.1.199 

$ ip -6 route show table all

$ ip rule
0:	from all lookup local
32764:	from all lookup main suppress_prefixlength 0
32765:	not from all fwmark 0xe1f1 lookup 205
32766:	from all lookup main
32767:	from all lookup default

$ ip -6 rule
0:	from all lookup local
32766:	from all lookup main

$ sysctl -a 2> /dev/null | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eno1.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.nordlynx.disable_ipv6 = 1

$ nmcli dev show | grep -E 'DNS|DEVICE'
GENERAL.DEVICE:                         eno1
IP4.DNS[1]:                             192.168.1.254
IP4.DNS[2]:                             75.153.171.124
GENERAL.DEVICE:                         nordlynx
GENERAL.DEVICE:                         lo

**Comment by ph202107** [comment]
Hi Marius!

I was able to test with a system running Linux Mint 21.1 and did not have the same problem, this issue seems to only affect the Mint 20.3 computer and only with 3.17.0.   Mint 20.3 is supported until April 2025 but I may need to upgrade sooner than expected.  Although based on Ubuntu I realize that Linux Mint is not on the officially supported distro list so unless you see an obvious problem I think the issue can be closed.  
Thank you for your time and attention to this matter.

**Comment by mariusSincovici** [comment]
Hi, 
Thank you for sending the logs. 
Unfortunately there isn't something obvious why it is not working, it might be something specific to Mint 20. We have an idea what caused this from the code, but to better understand I'll try to setup a machine.
As a possible workaround until we come with a solution this for NordLynx, would it be possible to check OpenVPN?

**Comment by ph202107** [comment]
Hi Marius!  I tested multiple times with OpenVPN UDP and OpenVPN TCP and it seems to be working OK, there is no DNS leak after I wake the computer from suspend.  I also noticed that with OpenVPN the uptime counter in "nordvpn status" resets to zero when waking the computer which does not happen with NordLynx.
I can use OpenVPN as a workaround until I upgrade the operating system.  Thanks for your help!

Here are the outputs when using OpenVPN UDP:

Technology: OPENVPN
Protocol: UDP
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: enabled
Threat Protection Lite: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled
Allowlisted subnets:
	192.168.1.0/24

Status: Connected
Hostname: us6309.nordvpn.com
IP: 172.93.177.187
Country: United States
City: Chicago
Current technology: OPENVPN
Current protocol: UDP
Transfer: 109.98 KiB received, 71.69 KiB sent
Uptime: 4 minutes 30 seconds

$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c8:d3:ff:a3:00:50 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.199/24 brd 192.168.1.255 scope global dynamic noprefixroute eno1
       valid_lft 86337sec preferred_lft 86337sec
4: nordtun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.8.2.4/24 scope global nordtun
       valid_lft forever preferred_lft forever

$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s 192.168.1.0/24 -i eno1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A INPUT -p udp -m multiport --dports 4000,5353 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 4000 -j ACCEPT
-A INPUT -p udp -m multiport --dports 5353 -j ACCEPT
-A OUTPUT -d 192.168.1.0/24 -o eno1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ sudo ip6tables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A INPUT -i eno1 -m comment --comment nordvpn -j DROP
-A INPUT -p udp -m multiport --dports 4000,5353 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 4000 -j ACCEPT
-A INPUT -p udp -m multiport --dports 5353 -j ACCEPT
-A OUTPUT -o eno1 -m mark --mark 0xe1f1 -m comment --comment nordvpn -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -o eno1 -m connmark --mark 0xe1f1 -m comment --comment nordvpn -j ACCEPT
-A OUTPUT -o eno1 -m comment --comment nordvpn -j DROP

$ ip route show table all
default dev nordtun table 205 scope link 
default via 192.168.1.254 dev eno1 proto dhcp metric 20100 
10.8.2.0/24 dev nordtun proto kernel scope link src 10.8.2.4 
169.254.0.0/16 dev eno1 scope link metric 1000 
192.168.1.0/24 dev eno1 proto kernel scope link src 192.168.1.199 metric 100 
broadcast 10.8.2.0 dev nordtun table local proto kernel scope link src 10.8.2.4 
local 10.8.2.4 dev nordtun table local proto kernel scope host src 10.8.2.4 
broadcast 10.8.2.255 dev nordtun table local proto kernel scope link src 10.8.2.4 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
broadcast 192.168.1.0 dev eno1 table local proto kernel scope link src 192.168.1.199 
local 192.168.1.199 dev eno1 table local proto kernel scope host src 192.168.1.199 
broadcast 192.168.1.255 dev eno1 table local proto kernel scope link src 192.168.1.199 

$ ip -6 route show table all

$ ip rule
0:	from all lookup local
32764:	from all lookup main suppress_prefixlength 0
32765:	not from all fwmark 0xe1f1 lookup 205
32766:	from all lookup main
32767:	from all lookup default

$ ip -6 rule
0:	from all lookup local
32766:	from all lookup main

$ sysctl -a 2> /dev/null | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eno1.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.nordtun.disable_ipv6 = 1

$ nmcli dev show | grep -E 'DNS|DEVICE'
GENERAL.DEVICE:                         eno1
IP4.DNS[1]:                             192.168.1.254
IP4.DNS[2]:                             isp.x.x.124
GENERAL.DEVICE:                         nordtun
GENERAL.DEVICE:                         lo

**Comment by mariusSincovici** [comment]
Hi,
the new released version 3.17.1 has a fix for this. Could you please try to update and see if it everything is ok for you?

**Comment by ph202107** [comment]
Hi Marius!  This issue appears to be resolved.  Using Linux Mint 20.3, NordVPN Version 3.17.1,  NordLynx, and connecting to https://dnscheck.tools/ I have no DNS leaks before or after suspend.  I also confirmed that there are no problems when using OpenVPN UDP.   Thank you!

However (perhaps related to the same changes) on my Linux Mint 21.3 computer I have disabled IPv6 via grub as recommended elsewhere to be a reliable method. (GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1" GRUB_CMDLINE_LINUX="ipv6.disable=1").  This has been working fine with NordVPN versions prior to 3.17.1.   With 3.17.1 I get this error when connecting to VPN:

$ nordvpn connect chicago
Connecting to United States #6722 (us6722.nordvpn.com)
The VPN connection has failed. Please check your internet connection and try connecting to the VPN again. If the issue persists, contact our customer support.

and this as the last line in the nordvpnd logs:
Feb 12 11:15:32 computer nordvpnd[631680]: 2024/02/12 11:15:32 [Error] retrieving the value of 'net.ipv6.conf.all.disable_ipv6': listing sysctl rules error: exit status 255: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory

Removing the GRUB entries, and with the IPv6 entries in /etc/sysctl.conf as recommended here:  https://support.nordvpn.com/hc/en-us/articles/20164669224337-How-to-disable-IPv6-on-Linux  it is working OK, no problems.

I thought I should mention it.  Can you advise if there are actually any benefits in using grub instead of sysctl.conf to disable IPv6? I do not know.

**Comment by mariusSincovici** [comment]
Hi,
as far as I saw the difference between `grub` and `sysctl` is that with grub IPv6 module is not loaded by the kernel. But sysctl is just controlling the state of IPv6.

We've registered a bug for the grub problem and we'll try to fix it as soon as possible.
thanks

**Comment by mariusSincovici** [comment]
hi @ph202107,
There is a new release 3.17.2 in which the IPv6 problem was fixed.

**Comment by ph202107** [comment]
Hi Marius!  I tested with "ipv6.disable=1" in GRUB and the VPN connects without any issues.  Everything seems to be working OK.  Thank you!
