### ISSUE TITLE
Wrong `dns --help` command option suggestions

### ISSUE THREAD

**Issue by corradom** [NordSecurity/nordvpn-linux#262]
Hi
while setting up my nordvp I noticed that the suggestion for `dns --help` command is wrong.

First I tried to 
```
❯ nordvpn set dns 
The command you entered has incorrect number of arguments. Enter 'nordvpn dns --help' to see the options.
```

Then, following the suggestion
```
❯ nordvpn dns --help 
Command 'dns' doesn't exist.
```

The correct one turned to be
```
❯ nordvpn set dns --help
Usage: nordvpn set dns [command options] <servers>|<disabled>
...
```

For reference
❯ nordvpn --version
**NordVPN Version 3.17.0**

**Comment by mariusSincovici** [comment]
Hi,
thank for your reporting the issue.
Yes, it seams that the help is broken in this case. I'll create an issue for this.

**Comment by corradom** [comment]
Just to add more information to the issue: I think the issue is not just for the vpn command.
For example I was trying to set autoconnect and the suggestion that I got on a wrong command is 

```
❯ nordvpn set autoconnect          
The command you entered has incorrect number of arguments. Enter 'nordvpn autoconnect --help' to see the options.
```

but `nordvpn autoconnect` does not exist.

```
❯ nordvpn autoconnect           
Command 'autoconnect' doesn't exist.
```

and the correct  one is 
```
❯ nordvpn set autoconnect --help
Usage: nordvpn set autoconnect [command options] <enabled>|<disabled> [<country>|<server>|<country_code>|<city>|<group>|<country> <city>]
...
```

**Comment by mariusSincovici** [comment]
it seams that there are more commands in this situation.
We'll review all of them and check which are incorrect.
thanks

**Comment by mariusSincovici** [comment]
Version 3.17.4 is available and should fix this.
Please update and let us know if you still have issues.
Thanks
