### ISSUE TITLE
Can not connect with version 3.17.1 in linux

### ISSUE THREAD

**Issue by serin-it** [NordSecurity/nordvpn-linux#266]
On Ubuntu 23.10 Nordvpn via the Linux command line app worked fine. For example I could connect using 'nordvpn c'.

With the latest version 3.17.1, when using the same command I get the following error:

'The specified server is not available at the moment or does not support your connection settings.'

When I revert back to version 3.17.0 of the Nordvpn app, it works.

**Comment by piotrjurkiewicz** [comment]
Could you tell what your `nordvpn settings` are?

**Comment by serin-it** [comment]
A screenshot of the settings are in the attached screenshot.

**Comment by piotrjurkiewicz** [comment]
@serin-it There is no attachment.

**Comment by serin-it** [comment]
Sorry about that. Should be attached now.

![Screenshot_20240212-221028](https://github.com/NordSecurity/nordvpn-linux/assets/18466010/5490b1f6-ef0e-4722-a081-9bbc60830863)

**Comment by piotrjurkiewicz** [comment]
OK, do you have IPv6 disabled in your system (the kernel, not NordVPN settings)? Could you check what is the result of the following command `cat /proc/sys/net/ipv6/conf/all/disable_ipv6`?

**Comment by serin-it** [comment]
The command `cat /proc/sys/net/ipv6/conf/all/disable_ipv6 `results in a response of 0

**Comment by irishbandit** [comment]
Downgrading to 3.17.0 works on Debian 12.

**Comment by irishbandit** [comment]
more info:
The command cat /proc/sys/net/ipv6/conf/all/disable_ipv6 results in
cat: /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory

I also run my kernels with ipv6.disable=1

**Comment by piotrjurkiewicz** [comment]
@serin-it @irishbandit Please check with the version 3.17.2 which was just released.

**Comment by serin-it** [comment]
Just checked 3.17.2 and it has the same issue as 3.17.1 unfortunately.

**Comment by irishbandit** [comment]
3.17.2 Works for me after restarting nordvpn and reconnecting.

**Comment by serin-it** [comment]
Version 3.17.2 works after logging out of my account and then logging back in. Thanks for the quick response in fixing.
