### ISSUE TITLE
can nordlynx and openvpn use the same interface and same IP?

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/nordvpn-linux#29]
Can nordlynx and openvpn use the same interface and same IP?
NordLynx calls the interface "nordlynx" and openvpn calls it "nordtun".

And can they have the same IP?
nordlynx is 10.5.0.2 and nordtun is 10.7.2.3

**Comment by Savolro** [comment]
Hi! Currently there are no plans to unify them or make it configurable

Regarding interface names, technically they don't matter much. In case you'd like to change them for yourself, you can change these hardcoded values.
OpenVPN: https://github.com/NordSecurity/nordvpn-linux/blob/57cea6a03932e6da2520b80c5ecc6644790ae098/daemon/vpn/openvpn/config.go#L46
NordLynx: https://github.com/NordSecurity/nordvpn-linux/blob/57cea6a03932e6da2520b80c5ecc6644790ae098/daemon/vpn/nordlynx/nordlynx.go#L20

IP, however is part of the information server has to know about. VPN servers will only respect traffic from the corresponsing subnets which are different per VPN technology. Without doing some kind of more sophisticated routing it is not possible to easily achieve this from the client side only.

**Comment by Savolro** [comment]
Closing issue as the question as answered and no follow-up questions were asked.
