### ISSUE TITLE
In most cases, NordVPN isn't connecting. This happens in the latest Ubuntu LTS and Kali.

### ISSUE THREAD

**Issue by TofuWand** [NordSecurity/nordvpn-linux#34]
setgokupikachu@127:~$ nordvpn connect
Connecting to United States #9467 (us9467.nordvpn.com)
Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.
setgokupikachu@127:~$ nordvpn settings
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: disabled
Threat Protection Lite: enabled
Obfuscate: enabled
Notify: enabled
Auto-connect: enabled
IPv6: enabled
Meshnet: disabled
DNS: disabled
setgokupikachu@127:~$ 
![Screenshot from 2023-06-26 20-26-57](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/8608a884-2891-40d9-ba37-57acf63b00ef)

...
Even with OpenVPN selected (that NordVPN told me to switch to before, it's not working. Also, the manual VPN option in my connection settings in the OS doesn't work either.

**Comment by EmilijusS** [comment]
Hello and thank you for the report.
1. Could you provide app logs after trying to connect to VPN? You can print them using `journalctl -e -u nordvpnd` command.
2. I see you have IPv6 setting enabled. Would it be possible for you to use IPv4? IPv6 support in our app is not as stable as IPv4 so that could rule out some possible issues.

**Comment by TofuWand** [comment]
[image: Screenshot from 2023-06-28 17-12-14.png]
Hi.

You're welcome, and thanks for the appreciation! Thanks for helping. I
tried disabling the IPv6 through the method on your site
<https://support.nordvpn.com/Connectivity/Linux/1047409212/How-to-disable-IPv6-on-Linux.htm>,
but it didn't work (edit the file, put the commands at the bottom of the
file, save, and reboot the device). I've attached a screenshot here. What
do I do now? Thanks! :3

Kind regards,
Seth

**Comment by TofuWand** [comment]
![image](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/01e72232-c3ab-4ad2-9219-dd7971b7692b)
![Screenshot from 2023-06-29 12-14-41](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/3229ff65-0f36-4391-8558-b1cc252d183e)
I noticed it didn't add the image from the reply I did via email. I'm glad I checked. lol

**Comment by EmilijusS** [comment]
Hi, you should also disable the IPv6 setting in the app via `nordvpn set ipv6 off`.

**Comment by TofuWand** [comment]
![Screenshot from 2023-06-29 14-11-00](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/d32b9c45-163c-4016-843e-0bbf3598237b)

Good to know, but it didn't help. What should I try now? Thanks.

**Comment by EmilijusS** [comment]
We would need app logs to investigate this issue. They can be printed using `journalctl -e -u nordvpnd` command.

**Comment by TofuWand** [comment]
It started working on my second attempt onward. Just to investigate this case further, I've supplied the system logs for NordVPN:

root@127:/home/setgokupikachu# journalctl -e -u nordvpnd
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 MANAGEMENT>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 OpenSSL: e>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS_ERROR:>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error:>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error:>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error:>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 MANAGEMENT>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 TLS: Initi>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29>
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 Get "https://api.>
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 rotated api trans>
Jun 29 17:17:13 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:13 error checking if>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 TLS: new s>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 MANAGEMENT>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29>
lines 978-1000/1000 (END)
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 MANAGEMENT: >STATE:1688055414,WAIT,,,,,,
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 MANAGEMENT: >STATE:1688055414,WAIT,,,,,,
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 OpenSSL: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record m>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 OpenSSL: error:1408F119:SSL routines:ssl3_get_record:decryption fa>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS_ERROR: BIO read tls_read_plaintext error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS_ERROR: BIO read tls_read_plaintext error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: TLS object -> incoming plaintext read error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: TLS object -> incoming plaintext read error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: TLS handshake failed
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: TLS handshake failed
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: Unroutable control packet received from [AF_INET]89.187.171.110:1216 (si=3 >
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: Unroutable control packet received from [AF_INET]89.187>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 MANAGEMENT: >STATE:1688055429,AUTH,,,,,,
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29 17:17:09 MANAGEMENT: >STATE:1688055429,AUTH,,,,,,
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 TLS: Initial packet from [AF_INET]89.187.171.110:1216, sid=f6d26bd6 5ac52bc3
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29 17:17:09 TLS: Initial packet from [AF_INET]89.187.171.110:1216, sid=f6d26bd>
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 Get "https://api.nordvpn.com/v1/users/services": lookup api.nordvpn.com on 103.86.99.100:53: >
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 rotated api transport to: std-http-transport
Jun 29 17:17:13 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:13 error checking if feature is version compatible: could not get min version for feature FILESH>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 TLS: new session incoming connection from [AF_INET]89.187.171.110:1216
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29 17:17:24 TLS: new session incoming connection from [AF_INET]89.187.171.110:>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 MANAGEMENT: >STATE:1688055444,WAIT,,,,,,
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29 17:17:24 MANAGEMENT: >STATE:1688055444,WAIT,,,,,,
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 978-1000/1000 (END)
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 MANAGEMENT: >STATE:1688055414,WAIT,,,,,,
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 MANAGEMENT: >STATE:1688055414,WAIT,,,,,,
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 OpenSSL: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad re>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 OpenSSL: error:1408F119:SSL routines:ssl3_get_record:decrypt>
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS_ERROR: BIO read tls_read_plaintext error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS_ERROR: BIO read tls_read_plaintext error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: TLS object -> incoming plaintext read error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: TLS object -> incoming plaintext read error
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: TLS handshake failed
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: TLS handshake failed
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:16:54 TLS Error: Unroutable control packet received from [AF_INET]89.187.171.110:1216 >
Jun 29 17:16:54 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:16:54 [INFO] 2023-06-29 17:16:54 TLS Error: Unroutable control packet received from [AF_INET]>
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 MANAGEMENT: >STATE:1688055429,AUTH,,,,,,
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29 17:17:09 MANAGEMENT: >STATE:1688055429,AUTH,,,,,,
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:09 TLS: Initial packet from [AF_INET]89.187.171.110:1216, sid=f6d26bd6 5ac52bc3
Jun 29 17:17:09 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:09 [INFO] 2023-06-29 17:17:09 TLS: Initial packet from [AF_INET]89.187.171.110:1216, sid=f>
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 Get "https://api.nordvpn.com/v1/users/services": lookup api.nordvpn.com on 103.86.99.10>
Jun 29 17:17:10 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:10 rotated api transport to: std-http-transport
Jun 29 17:17:13 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:13 error checking if feature is version compatible: could not get min version for feature >
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 TLS: new session incoming connection from [AF_INET]89.187.171.110:1216
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29 17:17:24 TLS: new session incoming connection from [AF_INET]89.187.17>
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: debug: 2023-06-29 17:17:24 MANAGEMENT: >STATE:1688055444,WAIT,,,,,,
Jun 29 17:17:24 127.0.0.1 nordvpnd[2760]: 2023/06/29 17:17:24 [INFO] 2023-06-29 17:17:24 MANAGEMENT: >STATE:1688055444,WAIT,,,,,,
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 978-1000/1000 (END)

![Screenshot from 2023-06-29 17-26-22](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/dff5e88e-b1ae-4606-9a7e-1f2304e211b9)
![Screenshot from 2023-06-29 17-26-19](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/a7984b13-3b31-4690-9a99-16ab8cdb3297)
![Screenshot from 2023-06-29 17-26-14](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/aec200c6-d4f1-479d-bfca-ecbb1f8eea07)
![Screenshot from 2023-06-29 17-26-06](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/ec523904-3bde-4f77-9256-32cead8edfec)
![Screenshot from 2023-06-29 15-19-45](https://github.com/NordSecurity/nordvpn-linux/assets/117850518/e9abfc9d-8c1a-451b-95b4-95a54873be97)

**Comment by EmilijusS** [comment]
Glad to know it works now. 
If it stops working again you could also try doing `nordvpn set technology nordlynx`, maybe other technology would work better for you.

**Comment by TofuWand** [comment]
> 

Thanks! It worked on the second attempt at connecting after I switched to that technology. Also, is there a way to make sure auto-connect works for Linux? It works just fine on Windows, Brave Nightly Beta plugin, and Android, but it has issues with Linux.
![Uploading Screenshot from 2023-06-30 19-13-29.png…]()

**Comment by EmilijusS** [comment]
Improvements to auto-connect are coming in the next version, which we will release in ~2 weeks.

**Comment by TofuWand** [comment]
> Improvements to auto-connect are coming in the next version, which we will release in ~2 weeks.

Awesome! Thanks a bunch! :3 That'll make the kill switch experience better then. Hehe. Very useful too with Kali for bug bounties, pen testing, etc. I'm an affiliate of NordSecurity, so I've been enjoying the fear year of NordVPN for several months now. Hehe. Thanks again to your team! <3 😅🤝🔥😻 NordVPN is on many of the most popular ethical hacking YouTube channels, too.

The latest updates for NordPass are great, too! The whole special pass feature being rolled out is absolutely amazing! 😅 It's gonna blow away Bitwarden. 

The next step is for NordSecurity is to roll out a cloud to compete with AWS, Linode, etc. To run dockers to have OSs in the browser for variety of OSs (Kali, Ubuntu, Debian, Windows 11, Mint, etc.), to have true sandboxes, and other stuff to run, too. 

I'm finally getting into clouding with Linode, and [Kasm](https://kasmweb.com/docs/latest/install/system_requirements.html#docker-and-docker-compose). I'm getting my first-ever tablet soon, too. I have a nonfunctioning Windows all-in-one tablet.

The [Blackview 16](https://s.lazada.com.ph/s.SkRZL) , that has an 11" screen, 250GB memory, 8GB RAM, plus boost RAM, too, is what I'm getting. It's got great reviews, and doesn't look like the many knockoffs on Lazada. Lol 😅

I'm getting enough money for it tomorrow to order it on Lazada. I already ordered a clear case for it. Hehe. 

I was gonna get a Xiaomi Tab 5, but the Blackview is much cheaper, brings some accessories, and it has more RAM than the Xiaomi Pad 5. I'm gonna root it to put Kasm in Linode, and run it on there. 

Then I can process the systems with cloud RAM, clearing all activities easily per session, Whonix, and more multitasking. I just gotta root it. Lol. 😅 My first time to root, and of course to be very careful about such activity. GitHub has [instructions](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27)  for putting a docker on it. 
https://github.com/MustardChef/WSABuilds

GitHub also has a [Windows 11 version for the tablet](https://github.com/MustardChef/WSABuilds)  that you just hit a Windows button for in the Android OS to switch to. So, that's cool. Plus, the Android OS on that device has a PC mode.

I can just run Windows 11 and other Windows in the docker though. 

Have a good one! ;3 😅🤝🔥🤓💯🤝
