### ISSUE TITLE
can't connect on Raspberry Pi 4 with v3.17.3

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/nordvpn-linux#342]
I upgraded my raspberry pi to nordvpn v 3.17.3 and I can't connect anymore.
I logged out and logged back in but that doesn't help.
I don't have a gui on this machine.
I tried both wireguard and openvpn (I prefer wireguard :-)).

```

$ sudo nordvpn c US
Connecting to United States #6270 (us6270.nordvpn.com)
The VPN connection has failed. Please check your internet connection and try connecting to the VPN again. If the issue persists, contact our customer support.
```

These are the only warnings or error from the log:
```

$ sudo journalctl -u nordvpnd

[Warning] executing 'ip -6 rule del from all lookup main suppress_prefixlength 0' command: exit status 2: RTNETLINK answers: No such file or directory

[Warning] executing 'ip -6 rule del not from all fwmark 57841' command: exit status 2: RTNETLINK answers: No such file or directory

[Error] networker setting dns: setting dns with resolvectl: setting dns with resolvectl: Failed to set DNS configuration: Unit dbus-org.freedesktop.resolve1.service not found.: exit status 1

```

**Comment by bjlockie** [comment]
I googled the error:

```
$ sudo systemctl start systemd-resolved.service
$ sudo systemctl enable systemd-resolved.service
```
fixed it.

**Comment by saus23** [comment]
same issue, my dns resolver is dnscrypt-proxy and was working fine with it before this update

**Comment by mariusSincovici** [comment]
Thank your for reporting the issue! We are investigating and we'll release a fix for systemd.
@saus23 could you please let us know what error message are you receiving?

**Comment by saus23** [comment]
Hello, here is the error that shows in journal.

[Error] networker setting dns: setting dns with resolvectl: setting dns with resolvectl: Failed to set DNS configuration: Could not activate remote peer: activation request failed: unknown unit.: exit status 1

It seems the update is now trying to use systemd-resolved, though I keep it disabled and "resolvectl" normally doesn't do anything on my system. If I allow resolved to set my dns, dig shows my own loopback address instead of a nordvpn assigned one

**Comment by mariusSincovici** [comment]
Sorry for the late response.
Version 3.17.4 is available, could you please try to update and see if it fixes your issues?

**Comment by saus23** [comment]
sorry im not having much luck building it with mage and docker. I was using the nordvpn-bin package on the arch aur.

**Comment by bjlockie** [comment]
Seems fixed.
