### ISSUE TITLE
nf_conntrack: nf_conntrack: table full, dropping packet

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/nordvpn-linux#36]
I'm getting a lot these and my wifi drops out.
Is this related to nordvpn?

```
$ sysctl net.netfilter.nf_conntrack_max                                 
net.netfilter.nf_conntrack_max = 524288
```

**Comment by keliramu** [comment]
Hello and thank you for a feedback,
We haven't experienced such problem yet. 
Could you give us more information by running command `conntrack -L` ?

**Comment by bjlockie** [comment]
It's bigger than I expected.

>conntrack v1.4.6 (conntrack-tools): 1959 flow entries have been shown

It's a Raspberry Pi 4.
I think it is underpowered.

**Comment by keliramu** [comment]
Hello, @bjlockie, could you give us more details on your situation? Is it persisting?
Have you identified the situation as abnormal nigh network traffic? Maybe you observed the source of traffic?
That could explain overload and having underpowered hardware.
Or maybe you have other details - that information could help us find the problem in our app and improve.

**Comment by bjlockie** [comment]
I installed a different OS and the problem went away.
