### ISSUE TITLE
v3.16.4: GOCOVERDIR not set, no coverage data emitted

### ISSUE THREAD

**Issue by tmknight** [NordSecurity/nordvpn-linux#41]
Seems a test parameter was left in the latest release - was `cover` really intended for the release binary?

The following generated with every exec of nordvpn:
`warning: GOCOVERDIR not set, no coverage data emitted`

**Comment by ZenInTexas** [comment]
v3.16.4, just installed - can confirm stdout message whenever nordvpn is run from command line: 
`warning: GOCOVERDIR not set, no coverage data emitted`

**Comment by keliramu** [comment]
Hello, yes, that minor glitch slipped through our control. We are planning a hot fix in coming days.

**Comment by keliramu** [comment]
Hello, yesterday we released hot-fix version 3.16.5 to remove that annoying message. @tmknight  @ZenInTexas - please update and accept our apologies for inconvenience.

**Comment by keliramu** [comment]
See release here: https://github.com/NordSecurity/nordvpn-linux/releases/tag/3.16.5
Closing issue.

**Comment by tmknight** [comment]
The fix is good - well done on the quick turnaround
