### ISSUE TITLE
NordVPN Linux 3.18.1 Tray icon does not load on cold boot

### ISSUE THREAD

**Issue by jrichard326** [NordSecurity/nordvpn-linux#425]
NordVPN 3.18.1, Manjaro Linux Xfce, Unstable branch

On cold boot the tray icon does not always appear in the panel. It will appear after launching nordvpn via terminal or by clicking the blank tray area where icon is supposed to be an connecting that way. After that the icon stays in the panel for the rest of the session.

Cold boot and manual launch:
2024/05/23 05:46:00.702327 main.go:92: Tray ready
2024/05/23 05:46:00.719244 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 05:46:00.725933 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 05:46:03.704853 notifications.go:44: [Info] Started dbus notifier

More complete Log:

2024/05/23 05:46:00.702327 main.go:92: Tray ready
2024/05/23 05:46:00.719244 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 05:46:00.725933 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 05:46:03.704853 notifications.go:44: [Info] Started dbus notifier
2024/05/23 06:01:03.799711 main.go:155: Received signal:  terminated
2024/05/23 06:01:03.799841 fileshare.go:44: [Info] Stopping fileshare
2024/05/23 06:01:03.800152 fileshare.go:46: [Error] failed to stop fileshare on shutdown:  stopping fileshare client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/fileshare.sock: connect: no such file or directory"
2024/05/23 06:01:03.800192 main.go:87: Tray exit at 2024-05-23 06:01:03.800180685 -0400 EDT m=+923.590535443
2024/05/23 06:01:04.300643 main.go:172: Norduser process has stopped
2024/05/23 06:01:24.561238 main.go:319: [Info] Daemon has started
2024/05/23 06:01:34.572139 main.go:92: Tray ready
2024/05/23 06:01:34.589270 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 06:01:34.596011 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 06:01:37.573388 notifications.go:44: [Info] Started dbus notifier
2024/05/23 18:08:38.712223 main.go:155: Received signal:  terminated
2024/05/23 18:08:38.712436 fileshare.go:44: [Info] Stopping fileshare
2024/05/23 18:08:38.712819 fileshare.go:46: [Error] failed to stop fileshare on shutdown:  stopping fileshare client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/fileshare.sock: connect: no such file or directory"
2024/05/23 18:08:38.712873 main.go:87: Tray exit at 2024-05-23 18:08:38.712858434 -0400 EDT m=+43633.251063893
2024/05/23 18:08:39.213087 main.go:172: Norduser process has stopped
2024/05/23 18:08:59.768182 main.go:319: [Info] Daemon has started
2024/05/23 18:09:09.785279 main.go:92: Tray ready
2024/05/23 18:09:09.802621 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 18:09:09.809190 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/23 18:09:12.786940 notifications.go:44: [Info] Started dbus notifier
2024/05/23 22:17:10.127767 main.go:155: Received signal:  terminated
2024/05/23 22:17:10.127926 fileshare.go:44: [Info] Stopping fileshare
2024/05/23 22:17:10.128296 fileshare.go:46: [Error] failed to stop fileshare on shutdown:  stopping fileshare client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/fileshare.sock: connect: no such file or directory"
2024/05/23 22:17:10.128348 main.go:87: Tray exit at 2024-05-23 22:17:10.128336678 -0400 EDT m=+14889.735925534
2024/05/23 22:17:10.629279 main.go:172: Norduser process has stopped
2024/05/24 05:38:44.706854 main.go:319: [Info] Daemon has started
2024/05/24 05:38:54.717677 main.go:92: Tray ready
2024/05/24 05:38:54.733907 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/24 05:38:54.740378 notifications.go:22: [Error] failed to send notification:  dbus notifier not connected
2024/05/24 05:38:57.718878 notifications.go:44: [Info] Started dbus notifier

**Comment by jrichard326** [comment]
Thank you for looking into this. The issue is very intermittent and I cannot reproduce it reliably either. I do not install it any differently than you indicate. I download and extract  the snapshot from AUR and I call makepkg.

Since this is so intermittent and not reproducible the issue can be closed unless others report the same issue with something in the logs.

Thanks again for your time and consideration.

JR

**Comment by mariusSincovici** [comment]
Ok, thanks.
Then I'll close it for now, but please reopen it if it will reproduce after the next release.
