### ISSUE TITLE
Meshnet crashed my system. 

### ISSUE THREAD

**Issue by justresisting** [NordSecurity/nordvpn-linux#426]
Before I outline the bug please note the following:

This is the first time I've seen an established service not have an issue template for how to respond to their bugs. I'm not a programmer and I don't know all of the info you need to effectively mitigate bugs. 

A template like the one laid out below customized for Nord services would help ensure you receive the information required with the fewest steps possible. 

---
> OS Information
> Expected Behavior
> Current Behavior
> Possible Solution
> Steps to Reproduce
> Context (Environment)
> Detailed Description
> Possible Implementation

---

> Hardware Model
> Memory
> Processor
> Graphics
> Disk Capacity
> Desktop Environment Version
> OS Name
> OS Type
> Windowing System
> Kernel Version
---

The problem effecting me is severe for an end user. 

I don't know what network information to include. 

People on Github are helping Nord solve problems for free. 

Please make it easy for us to do that. 

--- 

The most recent NordVPN for Linux update made me unable to access the internet.

### Expected Behavior

> I expected to turn on my computer as always and have NordVPN auto-connect and be able to access the internet and use my system normally. 

### Current Behavior

> When I turned on my computer there was no connection to the internet. There was a system update right before which updated the NordVPN Linux app. A system tray item appeared in my tray to access Linux app services but everything was grayed out. I tried to connect using the command line interface but it kept saying, "The VPN service was not accessible" in red. (These arent the exact words, I didn't copy and paste them).

### Possible Solution

> I restarted my computer a few times and did so from different user accounts. Eventually I had to relogin to NordVPN using the token from the command line but that took three attempts to finally work after using two different user accounts (only my administrator account worked). 
> 
> Eventually everything worked itself out and I could access the internet.

### Steps to Reproduce

1. Upgrade to the newest version of the NordVPN for Linux App. 
2. Be Unable to access the internet.
3. Try to login until it works
4. Access the internet again.

---

This would have been the end of the problem except I went through the settings and saw meshnet was disabled. I turned meshnet and the killswitch back on.

In a few minutes my system crashed.

---

### Meshnet crashed my system

---

### Expected Behavior

> I expected to restart my system and auto-connect to Nord and have all of my devices accessible. 

### Current Behavior

> Not only did I lose the ability to connect to the internet before my system fully came online my Desktop Environment crashed. This happened about 5 times. Budgie is my Desktop Environment of choice. After the fifth crash I decided to see if the problem happened on Gnome.  

### Possible Solution

> When I opened my system using Gnome on X11 the system did not crash. 
> 
> I was able to turn off the killswitch and connect to the internet successfully. 
> 
> I disabled meshnet

### Steps to Reproduce

1. Turn on Meshnet on the newest version of the NordVPn for Linux app
2. Have the Budgie desktop crash.

---

> Hardware Model -- Dell Inc. OptiPlex ****
> Memory -- 32.0 GiB
> Processor -- Intel® Core™ i7-****
> Graphics -- Intel® HD Graphics ***
> Disk Capacity -- 2.0 TB
> Budgie Version -- 10.8
> OS Name -- Ubuntu 23.10
> OS Type -- 64-bit
> Windowing System -- X11
> Kernel Version -- Linux 6.5.0-35-generic

---

The problems with my system are now gone. 

Meshnet and killswitch were disabled by default.

If meshnet is a problem with the current NordVPN for Linux app then either remove the feature temporarily or don't release the new version.

It took 2.5 hours to fix my system and open a Github issue.

I greatly appreciate NordVPN's efforts to offer their services to Linux users and the time and effort the development team spends on making that possible. Thank you, sincerely, for that work. 

Please include some kind of template laying out the information required to fix issues like these. 

**I am more annoyed that I had to research Github Issues responses than I am when I thought my entire system was bricked for an hour.**

The information laid out here may not seem that severe. Being unable to access the internet isn't that severe. Having your system crash before it fully starts up **IS** a very severe problem. I thought reinstalling my entire Operating System was my only solution for a while.

I've been a Linux user since 2018. Logging into your user from a Desktop Environment that isn't one you use isn't an intuitive step for many Linux users.   

There is something happening between NordVPN and the Budgie desktop environment causing it to crash. 

Ill make a quick report on the [BuddiesofBudgie](https://github.com/BuddiesOfBudgie) so that they are aware of this issue. 

Thanks.

**Comment by justresisting** [comment]
I reported this bug over at the BuddiesOfBudgie repo in [this Github issue response.](https://github.com/BuddiesOfBudgie/budgie-desktop/issues/580)

**Comment by piotrjurkiewicz** [comment]
We think that this is related to the Budgie DE not being able to deal with the newly introduced tray icon. Could you check if it also happens on the latest supported Budgie DE version?

Also, FYI, with the next release (3.18.2) a setting to disable the tray icon (`nordvpn set tray off`) will be introduced, so it may prevent those crashes.
