### ISSUE TITLE
NordVPN 3.18.1 spams tray icons.

### ISSUE THREAD

**Issue by evguu** [NordSecurity/nordvpn-linux#427]
After updating nordvpn to 3.18.1, I observed my tray get immediately filled by hundreds of nordvpn icons, bringing the system to a halt in mere seconds.
Even worse. it continued to do the same after each PC reboot (which had to be done by powering off the PC since it was completely dead). 
I was able to put an end to this by disabling the nordvpn service in sysctl (using safeboot, since the system was completely unusable otherwise), but even then -- the issue reappeared when I relaunched the app manually (using "nordvpn status").
I was only able to continue using the system after rolling back to an old version.

Ubuntu 20.04.6 LTS.

**Comment by mariusSincovici** [comment]
hi,
thank you for your feedback.
We are working to fix this for the next release. At the moment the tray will be restarted by any nordvpn command.

Could you please check if your user ID has more than 4 digits, bigger than 9999?

**Comment by evguu** [comment]
> Could you please check if your user ID has more than 4 digits, bigger than 9999?

Where can I find this value?

**Comment by evguu** [comment]
> If you run in terminal `id` will print the UID value.

Yes, id for my user is greater than 9999. It is not for "nordvpn" user though. (Just in case it matters)

**Comment by mariusSincovici** [comment]
Thanks for checking. Yes, we have an issue related to this that will be fixed in the next release.
Until then please downgrade to a version 3.17.x to be able to use the app. It is also the possible option to change the user ID, but that can lead to other issues for the OS or other apps.

**Comment by mariusSincovici** [comment]
Version 3.18.2 was released. This should fix the issue with the spamming tray.
I'll close the ticket for now, but feel free to reopen if needed.
