### ISSUE TITLE
nordvpnd 100% use on one cpu core after logging out and back in to desktop session

### ISSUE THREAD

**Issue by robert-92** [NordSecurity/nordvpn-linux#428]
I use EndeavourOS with Plasma KDE 6.0.5 (on Wayland) and kernel 6.9.2. Nordvpn works well until I log out my user to SDDM and then log back in to the Wayland session, after this the CPU fan on my Ryzen 5950x spins up and checking the system monitor graphs and info confirms that nordvpnd is using one of the system cores at 100%, heating up my CPU unnecessarily. Logging out and back in does not fix the issue and the only solution is to restart the computer.

Please let me know how I can further be of help.

**Comment by acud** [comment]
I can say that this is happening to me too. I'm using Manjaro i3 with kernel `5.15.158-1-MANJARO`.
The process just pumps to 100% CPU some time after logging in, and the problem resolves after restarting the service with `systemctl` (not sure if I can say that it permanently resolves for the rest of the session until reboot, or until a later point where it sporadically resurfaces).

**Comment by robert-92** [comment]
> hi, thanks for reporting this. Is the problem caused by the nordvpnd process or by norduserd?

I just checked again and it is in fact the norduserd process that pegs one of my cores at 100% as listed in plasma system monitor and I can reproduce the issue every time if I log out of my session and log back in a few seconds later with the VPN connected. I'm also using the default settings with the NordLynx standard and of the course the VPN client is the latest that you guys offer.

Thanks for following up and let me know if I can help further.

EDIT: I've also noticed one interesting behaviour, when this happens the NordVPN system tray icon no longer loads.

**Comment by mariusSincovici** [comment]
Thanks for checking.
Yes, this is something known and we are working to fix this.
For now as a workaround, when is starts to use lots of CPU you can restart the nordvpn service, so you don't need to restart the computer.

**Comment by robert-92** [comment]
Thanks for the update, you guys did a great job on the system tray
indicator and it makes the client much more user friendly on Linux.

**Comment by acud** [comment]
> hi, thanks for reporting this. Is the problem caused by the nordvpnd process or by norduserd?

on my side it's `nordvpnd` (I don't have a `norduserd`).

**Comment by mariusSincovici** [comment]
@acud then in your case it is a different issue, that we're not able to reproduce, unless the system time is incorrect.
Could you check that your system time is correct? If it is correct, could create a ticket for customer support and send your logs there(because they might include private information)?

**Comment by enricojonas** [comment]
Same issue for me, Ubuntu 24.04. Workaround (sudo systemctl restart nordvpnd) works.

**Comment by mariusSincovici** [comment]
Version 3.18.2 was released. This should fix the problems with norduserd process.
I'll close the ticket for now, but feel free to reopen if needed.

**Comment by robert-92** [comment]
Thanks, I'm just following up to let you know that while the high CPU usage
issue is fixed, the NordVPN system tray applet will not load and appear in
the Plasma system tray on subsequent logins to my KDE session, I'm not sure
what the cause is.

**Comment by mariusSincovici** [comment]
Yes, we are working on this issue for the next release. I'll reopen it.
Until then to have the tray back as a workaround would be to turn off/on the tray.
Thanks

**Comment by mariusSincovici** [comment]
3.18.3 was released and should fix the problem with subsequent logins.

**Comment by robert-92** [comment]
Thank you, this is good to hear.

**Comment by mariusSincovici** [comment]
Closing this for now, if needed please reopen it or create new issue.
