### ISSUE TITLE
3.18.2 breaks forwarding

### ISSUE THREAD

**Issue by nW70M1** [NordSecurity/nordvpn-linux#472]
3.18.2 breaks forwarding through a VPN gateway the same as 3.18.1 does. Rolling back to 3.18.0 as the last working version resolves this issue.

**Comment by mariusSincovici** [comment]
hi,
thanks for reporting this.
We'll try to reproduce this and let you know in case we need any information.

**Comment by mariusSincovici** [comment]
@nW70M1 could you please provide details about your setup? And how are the external devices connecting to it?
Thanks

**Comment by nW70M1** [comment]
Devices are directed to the VPN gateway via PBR on a router. The VPN gateway is Debian with forwarding enabled and iptables rules for masquerade and forwarding between the machine's NIC and the nordlynx adaptor. This has always worked well up to versions 3.18.1 or 3.18.2.

**Comment by JasperHorn** [comment]
I'm also experiencing this. I'm running nordvpn on my Raspberry Pi (rpi5 8GB). It's connected to my router (and thus the internet) using a lan cable, and its wifi chip is used to set up a wifi network (clients of which I intend to be routed through nordvpn). I'm running nordvpn and both the subnet of the wifi and that of my router:a DHCP are in the allowlist. Port 67 is also in the whitelist to allow DHCP requests.

I was running nordvpn 3.18.2. My wifi was working, and when nordvpn was connected, wifi clients were able to access the internet. However, when nordvpn was connected, they weren't. I tried a lot of different settings, but couldn't get it to work.

Then I found this issue and downgraded to get 18.3.0 and suddenly everything worked as intended.

**Comment by keliramu** [comment]
Hi, thank you for patience, we reproduced the problem, identified root cause and now preparing a fix.

**Comment by keliramu** [comment]
As a temporary workaround for affected versions 3.18.1 and 3.18.2 you could turn LAN discovery on `nordvpn set lan-discovery on` and that would enable forwarding.

**Comment by keliramu** [comment]
Hi, after internal discussion, we came to the conclusion that `LAN discovery ON` is the right way to have a forwarding through the VPN connected gateway. And the fact that it was working before - is rather bug than a feature; i.e. allowing to forward lan traffic while vpn connected is a bug and will be fixed soon.

**Comment by keliramu** [comment]
@nW70M1, issue fixed - please check new release 3.18.4, will be waiting for your feedback.
