### ISSUE TITLE
On Fedora 41 installing nord from bash give me an error output

### ISSUE THREAD

**Issue by abud7eem** [NordSecurity/nordvpn-linux#673]
on the official site https://nordvpn.com/download/linux/

when you run " sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh) " on Fedora 41 you get the following error:

Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.

Fedora 41 released yesterday stable 
https://fedoramagazine.org/announcing-fedora-linux-41/

**Comment by keliramu** [comment]
Hello, Fedora 41 is very fresh and there is new dnf 5 config-manager which has changed its cli interface - yet we need to add support for it.

**Comment by bhups2k** [comment]
I've tried downloading the install.sh file and changing the command to:
        $SUDO dnf config-manager addrepo "${repo}"
but then the new error which comes up is:
Unknown argument "https://repo.nordvpn.com//yum/nordvpn/centos/x86_64" for command "addrepo". Add "--help" for more information about the arguments.

step by step i guess...

**Comment by bhups2k** [comment]
Actually... found the rpm file in https://repo.nordvpn.com/yum/nordvpn/centos/x86_64/Packages/n/ and manually downloaded and installed it instead for now.

Thanks :)

**Comment by sprokkel78** [comment]
There is this post on reddit about installing nordvpn on fedora41 : https://www.reddit.com/r/Fedora/comments/1ggc66q/using_nordvpn_on_fedora_41/

**Comment by svenjacobs** [comment]
I dug through the [install script](https://downloads.nordcdn.com/apps/linux/install.sh) and replicated what it would execute. If you want to add the repo manually to Fedora 41, you have to execute the following:

```
sudo rpm -v --import https://repo.nordvpn.com/gpg/nordvpn_public.asc
sudo dnf config-manager addrepo --id=nordvpn --set=name='NordVPN' --set=baseurl='https://repo.nordvpn.com/yum/nordvpn/centos/x86_64/'
```

You may have to change the last path argument of the second command if you're on a different CPU architecture than x86. Afterwards install NordVPN via

```
sudo dnf install nordvpn
```

**Comment by keliramu** [comment]
Hello, thank you for an input. PR is ready here: https://github.com/NordSecurity/nordvpn-linux/pull/676/files

**Comment by keliramu** [comment]
Hello, above mentioned PR has been merged. Now new install script can be used like this: `sh <(curl -sSf https://raw.githubusercontent.com/NordSecurity/nordvpn-linux/refs/heads/main/test/qa/install.sh)`.
Assuming this issue is related to install script and DNF5 support. Other issued related to Fedora old or new - should be registered as new issue. Closing this issue now.
