### ISSUE TITLE
Issue with AUR download 

### ISSUE THREAD

**Issue by sokol-usa** [NordSecurity/nordvpn-linux#684]
Hello!

I’m encountering an error while trying to install via AUR Arch User Repository, specifically I’m getting the message: 

Failure to download https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn_3.19.0_amd64.deb

It seems that the link is not reachable, which might be causing the installation to fail. Here are a few steps I’ve tried to troubleshoot and resolve the issue:

    Check Network Connection: First, I made sure my internet connection is stable and functioning properly.

    Verify the URL: I manually checked the URL in a browser, and it appears that the file may have been moved or is no longer available at that location.

    Update AUR Packages: I ran yay -Syu (or the equivalent command for your AUR helper) to ensure that all AUR packages are up to date, in case there was a newer version available that fixed this issue.

    Manual Download: If the file is crucial for installation, I could download it manually and place it in the appropriate directory, but I'm not certain about the best way to do that without breaking dependencies.

    Check Logs: I looked at the build logs for more specific error messages but didn’t find anything beyond the failed download.

    Seek Alternative Sources: Is there an alternative installation method I should consider, such as using a different package or an updated repository?

If anyone else has encountered this problem or has suggestions on how to proceed, I’d appreciate any input!

Thank you!

**Comment by devzbysiu** [comment]
Hello, sorry for that. We restructured the repositories and this URL is no longer valid. This needs to be addressed by the maintainers of the Arch Repo for nordvpn as we are not maintaining it directly. 

Sorry for the inconvenience

**Comment by sokol-usa** [comment]
Thank you for the information and the prompt response
