### ISSUE TITLE
nordvpnd.service causes slow boot times

### ISSUE THREAD

**Issue by haasn** [NordSecurity/nordvpn-linux#69]
In the [nordvpnd.service](https://github.com/NordSecurity/nordvpn-linux/blob/main/contrib/systemd/system/nordvpnd.service) file, you define both:

```systemd
[Unit]
After=network-online.target
Wants=network-online.target
[Install]
WantedBy=default.target
```

This causes a transitive dependency of `default.target` (usually `graphical.target`) on `network-online.target`, meaning that the entire boot process will now wait until a network connection has been established before allowing users to log in.. I think this presents an unnecessary source of slowdown, typically 30s longer boot times on my end (laptop establishing wifi connection), and I think the situation needs to somehow be re-evaluated.

**Comment by haasn** [comment]
It seems this issue can be mitigated by changing it to `After=network-online.target graphical.target`. But I'm not 100% sure, I will have to test it on next reboot.

**Comment by haasn** [comment]
> It seems this issue can be mitigated by changing it to `After=network-online.target graphical.target`. But I'm not 100% sure, I will have to test it on next reboot.

I can confirm that this override fixes my slow boot issue. (Though maybe it should be `After=default.target` rather than `graphical.target`)

**Comment by TheRoarkster** [comment]
Trying this workaround, but also posting to note that `nordvpnd` draws extensive CPU percentage.  This may be an artifact of the posted problem, but it happens throughout usage of the machine.  Also related - though I will confirm - may be the inability of my laptop to reconnect to internet after suspend.

**Comment by TheRoarkster** [comment]
> It seems this issue can be mitigated by changing it to `After=network-online.target graphical.target`. But I'm not 100% sure, I will have to test it on next reboot.

Can you clarify what the "it" is in the above comment?  Is it the text after `[Install]` or after `[Unit]`?

**Comment by haasn** [comment]
> > It seems this issue can be mitigated by changing it to `After=network-online.target graphical.target`. But I'm not 100% sure, I will have to test it on next reboot.
> 
> Can you clarify what the "it" is in the above comment? Is it the text after `[Install]` or after `[Unit]`? OR just post the updated file?

"After=" only goes into the "[Unit]" section, afaict. I can post a patch tomorrow if you want, right now I just have a local override in my /etc/systemd:

```
[Unit]
After=graphical.target network-online.target
```

**Comment by EmilijusS** [comment]
Hello. I have a few questions:
1. Could you provide more details why does wifi connection being established takes so long for you? Also what Linux distribution are you using? It would help us to reproduce the issue on our side.
2. Could you try removing the whole `[Install]` section with the `WantedBy` statement while keeping everything else unchanged and see if that also helps? We are considering not including this section by default with the next release.
3. Regarding the CPU usage comment - we are aware of such problem and are also working to fix it.

**Comment by EmilijusS** [comment]
@haasn @TheRoarkster Could you please provide answers for questions in my last message? We'd like to fix this issue but we need more information.
