### ISSUE TITLE
when nordvpn is active dhcp lease time for internet ip  does not renew

### ISSUE THREAD

**Issue by tm4ig** [NordSecurity/nordvpn-linux#76]
I have VPS with public internet ipv4 address and nordvpn client. This ip assigned automatically from vps provider dhcp server.
When I connect to nordvpn server from vps, vps  ip address lease time does not renew so after after ip lease time expire vps becomes unavailable from the Internet.

Only if I manualy add dhcp server or ports to nordvpn whitelist lease time  prolongation works.

Can You fix this problem?

my current environment
Ubuntu 22.04.3 LTS
NordVPN 3.16.5

**Comment by EmilijusS** [comment]
This is expected - no other connections than the one to the VPN server are allowed when connected, and to allow other connections they have to be whitelisted by source. Why doesn't the whitelist approach suit you?

**Comment by tm4ig** [comment]
So Must I manually adding dhcp address/ports for my vps? Is this normally nordvpn action for dhcp?

**Comment by EmilijusS** [comment]
Yes, whitelisting either dhcp server address or dhcp port works and is the recommended approach. Another alternative would be doing `nordvpn set lan-discovery on` that we just introduced in the 3.16.6 release.
