### ISSUE TITLE
Closest and best server in terms of ping

### ISSUE THREAD

**Issue by mbfakourii** [NordSecurity/nordvpn-linux#79]
I need to connect to the closest and best server in terms of ping, but the command 
```nordvpn connect```
works randomly and connects to a random country.

my nordvpn settings
```
Technology: OPENVPN
Protocol: UDP
Firewall: enabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: enabled
Kill Switch: disabled
Threat Protection Lite: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
```

**Comment by EmilijusS** [comment]
Hello. My guess is that the API requests to find the recommended server are being blocked (you could probably see that in the logs using `sudo journaltctl -e -u nordvpnd`), so as a fallback you get assigned a random server from the whole server list. In this case, if you want a closer server you will have to provide a country or a specific server manually as an argument to `nordvpn connect`.

**Comment by mbfakourii** [comment]
Alternate address for
```https://api.nordvpn.com/v1/servers/recommendations?limit=20```
Does not exist?

**Comment by piotrjurkiewicz** [comment]
As @EmilijusS wrote, API access is needed to determine the closest servers to connect. If you want a closer server you will have to provide a country or a specific server manually as an argument to `nordvpn connect`.

In some countries specific domain access blocking is being done by changing/removing entries for these domains in ISP DNS servers. So you can try to change your DNS server address to a public one (for example Cloudflare's `1.1.1.1`). Maybe it will help and make the API server accessible for you.
