### ISSUE TITLE
Notification icon missing

### ISSUE THREAD

**Issue by Nickwiz** [NordSecurity/nordvpn-linux#81]
### Summary:

Notifications uses non-existing icon `/var/lib/nordvpn/icon.svg`

### Detail:

The `notify` function uses the constant `IconPath`  when sending notifications:

https://github.com/NordSecurity/nordvpn-linux/blob/6fd88a4b694f353cef8b0b5daa4535d749dd4a29/daemon/notify.go#L45-L55

where `IconPath` is defined in constants; typically as `/var/lib/nordvpn/icon.svg`:

https://github.com/NordSecurity/nordvpn-linux/blob/6fd88a4b694f353cef8b0b5daa4535d749dd4a29/daemon/constants.go#L16

On install the icon file is copied to `/usr/share/icons/hicolor/scalable/apps/nordvpn.svg` :

https://github.com/NordSecurity/nordvpn-linux/blob/6fd88a4b694f353cef8b0b5daa4535d749dd4a29/ci/nfpm/template.yaml#L93-L94

but no link or copy is made to `/var/lib/`.

One could define `IconPath`  to use the `/usr/share/icons` path. (Or if any other approach is better).

### Quick Fix:

A quick fix for most until remedied.

```sh
sudo ln -s /usr/share/icons/hicolor/scalable/apps/nordvpn.svg /var/lib/nordvpn/icon.svg
```

**Comment by EmilijusS** [comment]
Thank you. I created https://github.com/NordSecurity/nordvpn-linux/pull/82 and this will be fixed with the next release.
