### ISSUE TITLE
minor bug: switching from openvpn/tcp to wireguard

### ISSUE THREAD

**Issue by bjlockie** [NordSecurity/nordvpn-linux#9]
I was using openvpn/tcp and I switched to wireguard.
It still says:
`Current protocol: TCP`

I tried:
`$ sudo nordvpn set protocol udp`
and it said:
`Protocol setting is not available when the set technology is not OpenVPN.`
The "Current protocol" should be change to UDP I think or it should not be displayed when the technology is nordlynx. :-)

**Comment by paulams** [comment]
Thank you for reporting this issue. We will be looking into it.

**Comment by bjlockie** [comment]
Protocol is no longer displayed for nordlynx.
Tested on NordVPN Version 3.16.3

```
$ sudo nordvpn settings                                                        
Technology: OPENVPN
Protocol: TCP
```
```
$ sudo nordvpn settings
Technology: NORDLYNX

```
